# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the "main" branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# Lint code
  linting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      statuses: write 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node env
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
      - name: Install deps
        run: npm ci 
      - name: Code liniting
        id: lint_code
        run: npm run lint
      - name: Write status
        if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: ${{ steps.lint_code.conclusion }}
          name: "${{ github.workflow }}/lint"
          url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          description: "Lint code"
          token: ${{secrets.GITHUB_TOKEN}}
          ignoreForks: false
      - name: Set status
        if: always()
        run : |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{secrets.TOKEN }}" \
          --data '{"event_type": "update_status", "client_payload": { \
          "ref": ${{github.ref}} , \
          "sha":${{github.sha}}, \
          "state": ${{ steps.lint_code.conclusion }} , \
          "context": "${{ github.workflow }}/lint" , \
          "description": "Lint code" \
          "url": 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          }' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
          
          

  
  # Test code
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node env
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
      - name: Install deps
        run: npm ci # Runs test in package
      - name: Run tests
        id: test_code
        run: npm test
      - name: Write status
        if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: ${{ steps.test_code.conclusion }}
          name: "${{ github.workflow }}/test"
          url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          description: "Test code"
          token: "${{secrets.TOKEN}}"
          ignoreForks: false
        

  
